### ISSUE TITLE
Deletion and stacking issue on replay.

### ISSUE THREAD

**Issue by steemdevelopment** [harpagon210/steemsmartcontracts#15]
When running replay it will stack the data in the data folder if you already have a data folder.

Something should be added to clear the data folder on replay. That or added to the guide to tell people to remove the data folder every time they replay.

**Edit**: Actually it should cycle through for duplicates and ignore the duplicates and only submit the data for missing blocks.

![580905c80d6184d2e8ba78b285cbb31c](https://user-images.githubusercontent.com/45399127/54961299-54640e00-4f1d-11e9-9e14-383dc1e0681f.png)

**Comment by harpagon210** [comment]
I've added a line to the wiki:

```Delete the "data" folder (if this folder is not deleted, the new blocks are going to be added to the old chain)```

When replaying, all the blocks needs to be reprocessed, so we won't implement something to handle the duplicates ;)
