### ISSUE TITLE
Checkpoint Immutability

### ISSUE THREAD

**Issue by inertia186** [harpagon210/steemsmartcontracts#40]
*As a private ssc node operator, I would like to ensure that all block numbers have the same hash on all nodes, so that I can ensure each node has deterministically built the same sidechain (for a given chain-id).*

The tender project has a rake task to verify the blockchain and build a list of block numbers and corresponding block hashes.  An example of this can be seen here:

https://steem-engine.rocks/checkpoints

![image](https://user-images.githubusercontent.com/494368/59959550-934b2680-946e-11e9-9ae4-9826f2416761.png)

The checkpoints in the above screen capture were built on a private node running b4885fd88e9b3f22accc9a8081e51e1ed4a8c565.

However, when checking if these checkpoints match against another node, they do not always match.  In this example, they match block zero, but after block `10000`, they no longer match.

When running this check on a block-by-block granularity, checkpoints diverge at block `4999` where my private node has trx_id `1c57afb2574791e5564c2394b7532cb7d8730a7e` but the public node has trx_id `1c57afb2574791e5564c2394b7532cb7d8730a7e-0`.

**AC**

- [ ] All checkpoints match when comparing between different nodes on the same chain-id.

**Comment by harpagon210** [comment]
the branch witnesses will be the last branch bringing changes to the "block" structure which will change the hashes. This is necessary to add fields to the block that weren't needed when not running any consensus mechanism. After deploying the 'witnesses' branch, the hashes won't change anymore. (and if it does, it will only affect future blocks and not the old ones)
