### ISSUE TITLE
Full Sidechain Replay Polling Times

### ISSUE THREAD

**Issue by inertia186** [harpagon210/steemsmartcontracts#41]
*As a private node operator, I would like to build the sidechain with my own local `steemd` node (without a third party `blocks.log` file), so that I can verify the sidechain.*

The problem is that, by default, it now takes about three days to rebuild the sidechain using nothing but `steemd` as a source for transactions.  This will only get longer over time.

It is possible to reduce the replay time from three days to about 8 hours if you modify the source code:

https://github.com/harpagon210/steemsmartcontracts/blob/1856691530cf969daaa9a39eed6fd198a63c7fa3/libs/Streamer.js#L12
https://github.com/harpagon210/steemsmartcontracts/blob/bffa07a2670ca0595e18640b1da15a5e369c909a/plugins/Streamer.js#L256

So, normally, when it's all caught up, 200 (libs) and 100 (plugins) seems fine (as addressed in issue: #18).  But when rebuilding the entire sidechain from `steemd`, pooling takes too long.

For example, if the polling time is modified to 20/10, this significantly reduces the time it takes to rebuild the sidechain from `steemd`.  However, I am not suggesting that we change these polling times to something static.  Instead, I'm recommending that it become calculated, based on how far behind main chain streaming is.

**Comment by harpagon210** [comment]
the streamer has been reworked, it is now working in a synchronous way meaning that there is no pollings anymore, when a Steem block is parsed and it has SSC transactions in it, the block is directly sent to the blockchain public in a synchronous way, the streaming resumes whenever the blockchain plugin is done processing the block (see commit https://github.com/harpagon210/steemsmartcontracts/commit/861ff6f3948da6b666eddc3df85558c8fa557b8a)
