### ISSUE TITLE
Normal  SIGTERM Shutdown Fails (on ^C)

### ISSUE THREAD

**Issue by inertia186** [harpagon210/steemsmartcontracts#44]
*As a private node operator, I would like to be able to stop my node cleanly, so I don't have to worry that `config.json` is wrong.*

Most of the time, when a node is running perfectly normal for hours or days (`npm run start`), when using `^C` to stop the node, `config.json` is not saved with the correct value in `startSteemBlock`.  If the node operator does not catch this situation, they're likely to start the node again and end up with duplicate blocks.

**Comment by inertia186** [comment]
Tried `^C` (`SIGTERM`) on `mongodb` branch while trying to rebuild the entire sidechain from `steemd`.  After running for a few hours, at sidechain block 36, the process completely ignores `^C`.

These were the processes still running:

```bash
$ ps -ax | grep seed
 2039 ?        Ssl   24:00 /usr/bin/node --max-old-space-size=8192 /home/inertia/src/steemsmartcontracts.seed/plugins/Database.js
 2050 ?        Ssl   19:06 /usr/bin/node --max-old-space-size=8192 /home/inertia/src/steemsmartcontracts.seed/plugins/Blockchain.js
 2088 ?        Ssl    5:22 /usr/bin/node --max-old-space-size=8192 /home/inertia/src/steemsmartcontracts.seed/plugins/Streamer.js
```

After failed `^C`, I did a `kill` on the `Streamer.js` process.  After that, the other two processes needed to be manually killed as well.

**Comment by harpagon210** [comment]
this issue has been addressed in the witnesses branch that will soon be merged to master, the process will now make sure that a Steem block can't be parsed twice. Also, the graceful shutdown mechanism received a few improvements in order to make sure the child processes are killed correctly.
