### ISSUE TITLE
Non numeric value in Tables -> balances -> balance

### ISSUE THREAD

**Issue by steemchiller** [harpagon210/steemsmartcontracts#46]
Steem Engine's RPC server returns a non numeric value (ends with carriage return) in the field 'balance' for my account and token 'GEEK':

<img src="https://user-images.githubusercontent.com/30645598/62936612-960d2c80-bdca-11e9-850a-bbd3a775c970.png">

```isNaN( "10000\r" )``` returns `false` in JS, so it must go through `parseFloat` and then be converted to string on the server side to prevent this.

**Comment by harpagon210** [comment]
This is not really an issue, the software uses https://github.com/MikeMcl/bignumber.js/ to handle floating numbers, I would advise to do the same on your front end as the native float type of JavaScript is very bad at dealing with floating numbers
