### ISSUE TITLE
 7 vulnerabilities (6 high, 1 critical) -> npm audit fix

### ISSUE THREAD

**Issue by imtase** [harpagon210/steemsmartcontracts#47]
After I used the `npm install` command (clone of the repository) I got a message of  7 vulnerabilities (6 high, 1 critical) concerning lodash and eslint-utils package.

![Capture](https://user-images.githubusercontent.com/7558058/67468208-4a9db700-f674-11e9-8ab3-853ee96d57c3.PNG)

I fixed it by running the command `npm audit fix`

**Comment by harpagon210** [comment]
this has been fixed in the witnesses branch which will soon be merged to master (see https://github.com/harpagon210/steemsmartcontracts/commits/witnesses)
