### ISSUE TITLE
Account Name Validation

### ISSUE THREAD

**Issue by inertia186** [harpagon210/steemsmartcontracts#49]
Tools should be provided so that contracts are able to do stateless validation of account names (without lookup), identical to the mainnet:

See: [`STEEM_MAX_ACCOUNT_NAME_LENGTH`](https://developers.steem.io/tutorials-recipes/understanding-configuration-values#steem_min_account_name_length)

**Comment by harpagon210** [comment]
I've just added a "isValidAccountName" method to the SmartContract API, see https://github.com/harpagon210/steemsmartcontracts/commit/b575a9abbab70be5d12108f3bc0d1167757228f2 and https://github.com/harpagon210/steemsmartcontracts/commit/3db35b1280034d3bda4f9778d894d43f867d7e4f

The validation has been taken from SteemJS (see https://github.com/steemit/steem-js/blob/63871f7fdc7b7884c6534fca8ed3851f49ec2393/src/utils.js#L8)

The "tokens" contract will be updated at the same time as the "witnesses" branch is released

**Comment by inertia186** [comment]
Looks great _!!_
